export const HIRAGANA_RAW = `
ひらがな|HIRAGANA|HIRAGANA
重要|じゅうよう|JUUYOU|IMPORTANTE
要点|ようてん|YOUTEN|PUNTO ESENCIAL
要約|ようやく|YOUYAKU|RESUMEN
要る|いる|IRU|NECESITAR
利用|りよう|RIYOU|USO / UTILIZACIÓN
便利|べんり|BENRI|CÓMODO / PRÁCTICO
金利|きんり|KINRI|TASA DE INTERÉS
有利|ゆうり|YUURI|VENTAJOSO
明細|めいさい|MEISAI|DETALLES
BOSS_FRAS|勉強したところを、もう一度復習しましょう。|BENKYOUSHITATOKOROWOMOUICHIDOFUKUSHUUSHIMASHOU|“REPASEMOS UNA VEZ MÁS LO QUE HEMOS ESTUDIADO”.
BOSS_FRAS|手袋が片方しかない。どこで落としたのだろう。|TEBUKURAGAKATAHOUSHIKANAIDOKODEOTOSHITANODAROU|“SOLO TENGO UN GUANTE. ¿DÓNDE LO HABRÉ JAVADO CAER?”.
BOSS_FRAS|飛行機や電車などを交通機関という。|HIKOUKIYADENSHANADOWOKOUTSUUKIKANTOIU|“A LOS AVIONES, TRENES, ETC., SE LES LLAMA MEDIOS DE TRANSPORTE”.
BOSS_FRAS|私は通学に往復３時間かかります。|WATASHIHATSUUGAKUNIOUFUKUSANJIKANKAKARIMASU|“TARDO TRES HORAS EN VIAJE DE IDA Y VUELTA PARA IR A LA ESCUELA”.
BOSS_FRAS|ここでは係員の指示通りに駐車してください。|KOKODEHAKAKARIINNOSHIJIDOORINICHUUSHASHITEKUDASAI|“POR FAVOR, ESTACIONE AQUÍ SIGUIENDO LAS INSTRUCCIONES DEL PERSONAL”.
BOSS_FRAS|この時刻表に電車の発車時刻が書いてあります。|KONOJIKOKUHYOUNIDENSHANOHASSHAJIKOKUGAKAITEARIMASU|“LOS HORARIOS DE SALIDA DE LOS TRENES ESTÁN ESCRITOS EN ESTE HORARIO”.
BOSS_FRAS|銀行員「整理券をお取りになってお待ちください。」|GINKOUINSEIRIKENWOOTORININATTEOMACHIKUDASAI|“EMPLEADO BANCARIO: “POR FAVOR, TOME UN BILLETE DE TURNO Y ESPERE”.”
BOSS_FRAS|朝からおなかの調子がよくない。|ASAKARAONAKANOHOUSHIGAYOKUNAI|“NO ME SIENTO BIEN DEL ESTÓMAGO DESDE LA MAÑANA”.
`.trim(); // El .trim() quita líneas vacías automáticamente